### ISSUE TITLE
"No working compiler found"

### ISSUE THREAD

**Issue by p-cauty** [rez0n/actions-github-release#13]
Hi, I'd like to report an issue I just ran into. To this day, I used the v1.1 of this GitHub Action to get the latest release associated with a repo. Today, I ran into a crash of the docker build of this action. I tried to update my workflow to use the v1.5 of your project but I still have the same error. I've attached the full workflow log for you to see. I have little-to-no knowledge in docker, gcc or python so I'm afraid I cannot help you more.

Let me know if you have any idea of what the problem could be. Thank you and have a nice day!
[logs.txt](https://github.com/rez0n/actions-github-release/files/7912970/logs.txt)
.

**Comment by rez0n** [comment]
Hi @phpitou 
This issue has been fixed in #12 but I've forgotten to publish a new version. It is already published as `@1.6`, you also can use `@main` this will able you to use the latest version from the main branch of this repository.

**Comment by p-cauty** [comment]
Hi, thank you for your fast response! It's working well with v1.6 🥳 Maybe you could consider to freeze the version of the docker images that your are using? This way, you can avoid old versions of your work to be broken by third-party updates 👍🏼

Have a nice day!
