### ISSUE TITLE
Quite slow

### ISSUE THREAD

**Issue by devedse** [rez0n/actions-github-release#15]
Currently it takes about 26 seconds to obtain the release. Could we maybe try to exclude building the docker container and rather invoke python directly?

**Comment by rez0n** [comment]
Hi @devedse 
Yes, this is not best execution time for such action. I have been applied update to reduce execution time (v1.8)
btw, there is no way to invoke python directly in the Github Actions packages, it could be as Javascript or Docker packages only.
