### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bruuuuuuuce** [rez0n/actions-github-release#2]
I would just like to raise the concern that this repo does not have any license associated with it. This prevents many people from using this github action, as the owner can change the license at any time, and cause people who use this issues in the future. If this project is meant to be used by the community, I would recommend that you add an apache 2.0 license so that people know they can safely use it. If its not intended to be used by the community though, then its ok as is! 

Just wanted to bring this up as someone who wanted to use this plugin, but was prevented from doing so by the lack of apache 2.0 license.

**Comment by rez0n** [comment]
Hi @bruuuuuuuce 
Sorry, my mistake. Licence added.
