### ISSUE TITLE
index out of range for assets list

### ISSUE THREAD

**Issue by samvaughton** [rez0n/actions-github-release#6]
Hi there,

Been using your geat actions package and got some build failures this morning due to this recent change here:

https://github.com/rez0n/actions-github-release/commit/763ba45917b3ed3b3ef7e9ddd42b9e1b62083a2d#diff-bbe1c7e8f028a2c298f6e76508251ff27f59c1f12450a8df6ddf2ec0a1464316R21

```
Traceback (most recent call last):
  File "/entrypoint.py", line 27, in <module>
    output(release)
  File "/entrypoint.py", line 21, in output
    print('::set-output name=browser_download_url::{}'.format(assets[0].browser_download_url))
  File "/usr/local/lib/python3.9/site-packages/github/PaginatedList.py", line 49, in __getitem__
    return self.__elements[index]
IndexError: list index out of range
```

I presume this is because the builds I am running do not contain any assets. If you are open to PR's I can add a conditonal check for aforementioned line?

Cheers, Sam

**Comment by MajdSehwail** [comment]
Hey, our builds are failing since morning due to this too.

**Comment by rez0n** [comment]
Hi @samvaughton 
Thanks for your fix.

@MajdSehwail Sorry for the issue.

**Comment by MajdSehwail** [comment]
Thanks for resolving the issue guys 😄

**Comment by rez0n** [comment]
My fail I'd not well tested it, sorry.
Let me know if something is still wrong (I hope no).

**Comment by samvaughton** [comment]
> Hi @samvaughton
> Thanks for your fix.

Should thank @darora ! :)

**Comment by rez0n** [comment]
Oops, @darora thanks for your fix :)
