### ISSUE TITLE
Index out of bounds still occurring

### ISSUE THREAD

**Issue by samvaughton** [rez0n/actions-github-release#9]
Issue is still occurring, I suspect due to assuming `assets` is falsey when performing the conditional check.

```
Traceback (most recent call last):
  File "/entrypoint.py", line 29, in <module>
    output(release)
  File "/entrypoint.py", line 21, in output
    dl_url = assets[0].browser_download_url if assets else '""'
  File "/usr/local/lib/python3.9/site-packages/github/PaginatedList.py", line 49, in __getitem__
    return self.__elements[index]
IndexError: list index out of range
```

I've submitted a PR #8 with more information inside.

**Comment by rez0n** [comment]
Hi @samvaughton 
this is strange because 
```
dl_url = assets[0].browser_download_url if assets else '""'
```
worked for me on tests.
But anyway your solution is better.

Thanks for the PR.

**Comment by samvaughton** [comment]
> Hi @samvaughton
> this is strange because
> 
> ```
> dl_url = assets[0].browser_download_url if assets else '""'
> ```
> 
> worked for me on tests.
> But anyway your solution is better.
> 
> Thanks for the PR.

Based on no one else replying today about it, I suspect it worked for others too - not sure why it failed for me!

Cheers
